interfaces/books/urls.py
from django.urls import path

from .views import IndexTemplateView, ContactFormView, BooksTemplateView, ReviewTemplateView, ProfileFormView

app_name = 'books'

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('shop/<str:category>-books/', BooksTemplateView.as_view(), name='shop'),
    path('shop/<str:category>-books/page-<int:page>/', BooksTemplateView.as_view(), name='paginator'),
    path('shop/review/book-<int:pk>/', ReviewTemplateView.as_view(), name='review'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('profile/', ProfileFormView.as_view(), name='profile'),
]

interfaces/interfaces/urls.py
from django.conf import settings
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('', lambda req: redirect('books/')),
    path('books/', include('books.urls', namespace='books')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')),)

interfaces/orders/urls.py
from django.urls import path

from orders.views import OrdersTemplateView, CurrentOrderTemplateView

app_name = 'orders'

urlpatterns = [
    path('order/', OrdersTemplateView.as_view(), name='order'),
    path('order/<int:pk>/', CurrentOrderTemplateView.as_view(), name='current'),
]

interfaces/orders/views.py
import datetime
import json
import requests
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import TemplateView
from rest_framework import status

from common.views import TitleMixin


class OrdersTemplateView(TitleMixin, TemplateView):
    template_name = 'orders/orders.html'

    def get(self, request, *args, **kwargs):
        token = request.COOKIES.get('Authorization')
        user_id = request.COOKIES.get('User')
        if token and user_id:
            headers = {'Authorization': f'Token {token}'}
            cookies = {'User': user_id}
            response = requests.get('http://127.0.0.1:8004/api/orders/current/',
                                    headers=headers, cookies=cookies)
            if response.status_code == status.HTTP_200_OK:
                self.extra_context = {'orders': json.loads(response.text)}
            else:
                return redirect(reverse('books:index'))
        else:
            return redirect(reverse('books:index'))
        return super().get(request, *args, **kwargs)


class CurrentOrderTemplateView(TitleMixin, TemplateView):
    template_name = 'orders/current-order.html'

    def get(self, request, *args, **kwargs):
        token = request.COOKIES.get('Authorization')
        user_id = request.COOKIES.get('User')
        if token and user_id:
            headers = {'Authorization': f'Token {token}'}
            cookies = {'User': user_id}
            order_id = kwargs.get('pk')
            response = requests.get(f'http://127.0.0.1:8004/api/orders/current/{order_id}/',
                                    headers=headers, cookies=cookies)
            if response.status_code == status.HTTP_200_OK:
                self.extra_context = {'order': json.loads(response.text)}

                date_string = self.extra_context['order']['created_timestamp']
                date = datetime.datetime.strptime(date_string, "%Y-%m-%dT%H:%M:%S.%fZ")
                self.extra_context['order']['created_timestamp'] = date
            else:
                return redirect(reverse('books:index'))
        else:
            return redirect(reverse('books:index'))
        return super().get(request, *args, **kwargs)

interfaces/orders/templates/orders/current-order.html
{% extends 'books/base.html' %}
{% load humanize %}


{% block content %}
<div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="colored">
					<h1 class="page-title">Order - #{{ order.order_number }}</h1>
					<div class="breadcum-items">
						<span class="item"><a href="{% url 'books:index' %}">Home /</a></span>
                        <span class="item colored">
                            <a href="{% url 'books:index' %}">Orders /</a> #{{ order.order_number }}
                        </span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div><!--site-banner-->

<section class="contact-information padding-large mt-3">
	<div class="container">
		<div class="row" style="display: flex; justify-content: space-between">
            <div class="col-md-4 p-0">

                <div id="info" style="position: sticky; top: 20px">
                    <h2>Personal information</h2>
                    <p style="margin-bottom: 10px">First name: <b>{{ order.first_name }}</b></p>
                    <p style="margin-bottom: 10px">Last name: <b>{{ order.last_name }}</b></p>
                    <p style="margin-bottom: 10px">E-mail: <b>{{ order.email }}</b></p>
                    <p style="margin-bottom: 10px">Phone: <b>{{ order.email }}</b></p>
                    <p style="margin-bottom: 10px">Address: <b>{{ order.email }}</b></p>
                    <p style="margin-bottom: 10px">Message: <b>{{ order.email }}</b></p>
                    <p style="margin-bottom: 10px">Created: <b>{{ order.created_timestamp }}</b></p>
				</div><!--contact-information-->

			</div><!--col-md-6-->
			<div class="col-md-4 p-0 mb-3">
				<h2 style="display: flex; justify-content: center">Products</h2>
				<div class="contact-detail d-flex flex-wrap mt-4">
					{% for current in order.extra_data %}
                    <figure class="product-style">
                        <a href="{% url 'books:review' current.book_id %}">
                            <img src="{{ current.image }}" alt="Books" class="product-item">
                        </a>
                        <figcaption>
                            <h3>{{ current.name }}</h3>
                            <p>Quantity: {{ current.quantity }}</p>
                            <div class="item-price">$ {{ current.price }}</div>
                        </figcaption>
                    </figure>
                {% endfor %}
				</div><!--contact-detail-->
			</div><!--col-md-6-->

		</div>
	</div>
</section>

{% endblock %}

interfaces/orders/templates/orders/orders.html
{% extends 'books/base.html' %}


{% block content %}
<div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="colored">
					<h1 class="page-title">Orders</h1>
					<div class="breadcum-items">
						<span class="item"><a href="{% url 'books:index' %}">Home /</a></span>
						<span class="item colored">Orders</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div><!--site-banner-->

<section class="padding-large">
	<div class="container">
		<div class="row">
            {% if orders %}
                <div class="products-grid grid">
                {% for order in orders %}
                    <figure class="product-style" style="display: flex; justify-content: center">
                        <a href="{% url 'orders:current' order.order_number %}">
                            <h3>Order - #{{ order.order_number }}</h3>
                        </a>
                    </figure>
                {% endfor %}
            {% else %}
                <div style="display: flex; justify-content: center">
                    <h2>You have not placed an order.</h2>
                </div>
            {% endif %}
	    	</div>
		</div>
	</div>
</section>
{% endblock %}