interfaces/books/urls.py
from django.urls import path

from .views import IndexTemplateView, ContactFormView, BooksTemplateView, ReviewTemplateView, ProfileFormView

app_name = 'books'

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('shop/<str:category>-books/', BooksTemplateView.as_view(), name='shop'),
    path('shop/<str:category>-books/page-<int:page>/', BooksTemplateView.as_view(), name='paginator'),
    path('shop/review/book-<int:pk>/', ReviewTemplateView.as_view(), name='review'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('profile/', ProfileFormView.as_view(), name='profile'),
]

interfaces/interfaces/urls.py
from django.conf import settings
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('', lambda req: redirect('books/')),
    path('books/', include('books.urls', namespace='books')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')),)

interfaces/users/urls.py
from django.shortcuts import redirect
from django.urls import path

from .views import UserLoginFormView, UserRegistrationFormView, EmailVerificationTemplateView

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginFormView.as_view(), name='login'),
    path('logout/', lambda req: redirect('http://127.0.0.1:8000/api/users/logout/'), name='logout'),
    path('registration/', UserRegistrationFormView.as_view(), name='registration'),
    path('verification/<str:email>/<uuid:code>/', EmailVerificationTemplateView.as_view(), name='email_verification'),

    path('accounts/google/', lambda req: redirect('http://127.0.0.1:8000/accounts/google/login/'), name='google'),
    path('accounts/github/', lambda req: redirect('http://127.0.0.1:8000/accounts/github/login/'), name='github'),
]

interfaces/users/forms.py
import requests
from django import forms
from rest_framework import status


class UserLoginForm(forms.Form):
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Username',
    }))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Password',
    }))

    def clean(self):
        cleaned_data = super().clean()
        data = {
            'username': cleaned_data.get('username'),
            'password': cleaned_data.get('password')
        }
        req = requests.post('http://127.0.0.1:8000/api/users/login/', data=data)
        if req.status_code == status.HTTP_400_BAD_REQUEST:
            raise forms.ValidationError(req.json().get('error'))

    def add_error(self, field, error):
        errors = self.errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(error)


class UserRegistrationForm(forms.Form):
    first_name = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'First name',
    }))
    last_name = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Last name',
    }))
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Username',
    }))
    email = forms.CharField(required=True, widget=forms.EmailInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'E-mail',
    }))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Password',
    }))
    password2 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={
        'class': 'form-control py-4',
        'placeholder': 'Confirm password',
    }))

    def clean(self):
        cleaned_data = super().clean()
        data = {
            'first_name': cleaned_data.get('first_name'),
            'last_name': cleaned_data.get('last_name'),
            'email': cleaned_data.get('email'),
            'username': cleaned_data.get('username'),
            'password': cleaned_data.get('password'),
        }
        if data['password'] != cleaned_data.get('password2'):
            raise forms.ValidationError('Password mismatch.')
        req = requests.post('http://127.0.0.1:8000/api/users/registration/', data=data)
        if req.status_code == status.HTTP_400_BAD_REQUEST:
            for error in req.json().get('errors').values():
                raise forms.ValidationError(error)

    def add_error(self, field, error):
        errors = self.errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(error)

interfaces/users/views.py
import requests
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, FormView
from rest_framework import status

from common.views import TitleMixin
from .forms import UserLoginForm, UserRegistrationForm


class UserLoginFormView(TitleMixin, FormView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    title = 'Book Store - Login'
    success_url = reverse_lazy('books:index')

    def form_valid(self, form):
        req = requests.post('http://127.0.0.1:8000/api/users/login/', data=form.cleaned_data)
        if req.status_code == status.HTTP_200_OK:
            response = super().form_valid(form)
            response.set_cookie('Authorization', req.cookies.get('Authorization'))
            response.set_cookie('User', req.cookies.get('User'))
            return response
        else:
            form._errors = req.json().get('text')
        return self.form_invalid(form)


class UserRegistrationFormView(TitleMixin, SuccessMessageMixin, FormView):
    template_name = 'users/registration.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('users:login')
    success_message = 'Registration was successful.\n' \
                      'Check your e-mail for verification this account.'
    title = 'Book Store - Registration'


class EmailVerificationTemplateView(TitleMixin, TemplateView):
    template_name = 'users/email_verification.html'
    title = 'Book Store - E-mail confirmation'

    def get(self, request, *args, **kwargs):
        code = kwargs['code']
        response = requests.get('http://127.0.0.1:8000/api/users/verification/', params={'code': code})
        if response.status_code == status.HTTP_200_OK:
            return super().get(request, *args, **kwargs)
        return HttpResponseRedirect(reverse('books:index'))

interfaces/users/templates/users/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'vendor/css/auth.css' %}" rel="stylesheet"/>
    <link href="{% static 'vendor/css/style.css' %}" rel="stylesheet"/>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>

<body class="bg-primary" style="background: #F3F2EC !important;">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        {% block content %}

        {% endblock %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'vendor/js/auth-admin.js' %}"></script>
</body>
</html>

interfaces/users/templates/users/email_verification.html
{% extends 'users/base.html' %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Congratulations</h3>
                        </div>
                        <div class="card-body text-center">
                            <h4>Your account has been successfully verified!</h4>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small"><a href="{% url 'books:index' %}">Continue</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

interfaces/users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    {% if messages or form.non_field_errors %}
                         <div class="alert
                         {% if messages %} alert-success {% else %} alert-warning {% endif %}
                         alert-dismissible fade show" role="alert"
                         style="margin-top: 50px;">
                         {% if messages %}
                             {% for message in messages %}
                                {{ message }}
                             {% endfor %}
                         {% else %}
                             {{ form.non_field_errors }}
                         {% endif %}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}

                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Authorization</h3>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'users:login' %}" method="post" style="margin-bottom: 10px">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.username.id_for_label }}">Username</label>
                                    {{ form.username }}
                                </div>
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.password.id_for_label }}">Password</label>
                                    {{ form.password }}
                                </div>
                                <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                    <a class="small" href="#">Forget password?</a>
                                    <input class="btn btn-primary btn-rounded" type="submit" value="Login"
                                           style="width: 100px">
                                </div>
                                <div style="display: flex; justify-content: center; margin-bottom: 0">
                                    <a href="{% url 'users:google' %}" style="height: 32px; margin-right: 25px">
                                        <i class="fab fa-google fa-2x" style="color: #d9503e;"></i>
                                    </a>
                                    <a href="{% url 'users:github' %}" style="height: 32px">
                                        <i class="fab fa-github fa-2x" style="color: #303030;"></i>
                                    </a>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center" style="margin-top: 0">
                            <div class="small"><a href="{% url 'users:registration' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

interfaces/users/templates/users/registration.html
{% extends 'users/base.html' %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    {% if form.non_field_errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                         style="margin-top: 50px;">
                            {{ form.non_field_errors }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}

                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'users:registration' %}" method="post" style="margin-bottom: 10px">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                            {{ form.first_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                            {{ form.last_name }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                                        {{ form.username }}
                                    </div>
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                            почты</label>
                                            {{ form.email }}
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                                            {{ form.password }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
                                                пароля</label>
                                            {{ form.password2 }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group mt-4 mb-0">
                                    <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small"><a href="{% url 'users:login' %}">Уже есть аккаунт? Авторизоваться</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}