interfaces/baskets/urls.py
from django.urls import path

from baskets.views import add_to_basket, remove_from_basket, BasketTemplateView, BasketFormView, SuccessTemplateView

app_name = 'baskets'

urlpatterns = [
    path('current/', BasketTemplateView.as_view(), name='basket'),
    path('current/checkout/', BasketFormView.as_view(), name='checkout'),
    path('current/checkout/success', SuccessTemplateView.as_view(), name='success'),
    path('add-<int:book_id>/', add_to_basket, name='add'),
    path('remove-<int:book_id>/', remove_from_basket, name='remove'),
]

interfaces/books/urls.py
from django.urls import path

from .views import IndexTemplateView, ContactFormView, BooksTemplateView, ReviewTemplateView, ProfileFormView

app_name = 'books'

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('shop/<str:category>-books/', BooksTemplateView.as_view(), name='shop'),
    path('shop/<str:category>-books/page-<int:page>/', BooksTemplateView.as_view(), name='paginator'),
    path('shop/review/book-<int:pk>/', ReviewTemplateView.as_view(), name='review'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('profile/', ProfileFormView.as_view(), name='profile'),
]

interfaces/interfaces/urls.py
from django.conf import settings
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('', lambda req: redirect('books/')),
    path('books/', include('books.urls', namespace='books')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')),)

interfaces/orders/urls.py
from django.urls import path

from orders.views import OrdersTemplateView, CurrentOrderTemplateView

app_name = 'orders'

urlpatterns = [
    path('order/', OrdersTemplateView.as_view(), name='order'),
    path('order/<int:pk>/', CurrentOrderTemplateView.as_view(), name='current'),
]

interfaces/users/urls.py
from django.shortcuts import redirect
from django.urls import path

from .views import UserLoginFormView, UserRegistrationFormView, EmailVerificationTemplateView

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginFormView.as_view(), name='login'),
    path('logout/', lambda req: redirect('http://127.0.0.1:8000/api/users/logout/'), name='logout'),
    path('registration/', UserRegistrationFormView.as_view(), name='registration'),
    path('verification/<str:email>/<uuid:code>/', EmailVerificationTemplateView.as_view(), name='email_verification'),

    path('accounts/google/', lambda req: redirect('http://127.0.0.1:8000/accounts/google/login/'), name='google'),
    path('accounts/github/', lambda req: redirect('http://127.0.0.1:8000/accounts/github/login/'), name='github'),
]

interfaces/books/forms.py
from django import forms


class MessageForm(forms.Form):
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={
                'class': 'u-full-width',
                'name': 'name',
                'placeholder': 'Name',
                'minlength': '2',
                'type': 'text',
    }))
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={
        'class': 'u-full-width',
        'name': 'email',
        'placeholder': 'E-mail',
        'type': 'email',
    }))
    message = forms.CharField(required=True, widget=forms.Textarea(attrs={
        'class': 'u-full-width',
        'name': 'message',
        'placeholder': 'Message',
        'style': 'height: 150px',
    }))


class ProfileForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'u-full-width',
        'name': 'name',
        'placeholder': 'First Name',
        'minlength': '2',
        'type': 'text',
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'u-full-width',
        'name': 'last_name',
        'placeholder': 'Last Name',
        'type': 'text',
    }))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'u-full-width',
        'name': 'username',
        'placeholder': 'Username',
        'minlength': '2',
        'type': 'text',
        'readonly': True,
        'style': 'background-color: #a4a4a4',
    }))
    email = forms.EmailField(widget=forms.TextInput(attrs={
        'class': 'u-full-width',
        'name': 'email',
        'placeholder': 'E-mail',
        'type': 'email',
    }))

interfaces/books/views.py
import json

import requests
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView
from django.core.cache import cache

from books.forms import MessageForm, ProfileForm
from common.views import TitleMixin


class IndexTemplateView(TitleMixin, TemplateView):
    template_name = 'books/index.html'
    title = 'Book Store'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        previews = cache.get('previews')
        recommendations = cache.get('recommendations')
        partners = cache.get('partners')

        if previews or recommendations or partners:
            context['previews'] = previews
            context['recommendations'] = recommendations
            context['partners'] = partners
        else:
            previews = requests.get('http://127.0.0.1:8001/api/books/previews/')
            context['previews'] = previews.json().get('results')
            cache.set('previews', context['previews'], 60)

            recommendations = requests.get('http://127.0.0.1:8001/api/books/recommendations/')
            context['recommendations'] = recommendations.json().get('results')
            cache.set('recommendations', context['recommendations'], 60)

            partners = requests.get('http://127.0.0.1:8001/api/books/partners/')
            context['partners'] = partners.json()
            cache.set('partners', context['partners'], 60)
        return context


class BooksTemplateView(TitleMixin, TemplateView):
    template_name = 'books/shop.html'
    title = 'Book Store - Products'

    def get(self, request, *args, **kwargs):
        category = kwargs.get('category')
        page = kwargs.get('page')
        self.extra_context = {'category': category}

        if category == 'all':
            if page:
                books = requests.get(f'http://127.0.0.1:8001/api/books/all/?page_number={page}')
            else:
                books = requests.get(f'http://127.0.0.1:8001/api/books/all/')
        else:
            if page:
                books = requests.get(str(f'http://127.0.0.1:8001/api/books/all/?page_number={page}'),
                                     params={'category': category})
            else:
                books = requests.get(f'http://127.0.0.1:8001/api/books/all/', params={'category': category})
        self.extra_context['all_books'] = books.json()
        return super().get(self, request, *args, **kwargs)


class ContactFormView(TitleMixin, FormView):
    template_name = 'books/contact.html'
    form_class = MessageForm
    success_url = reverse_lazy('books:contact')
    title = 'Book Store - Contact'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        response = requests.get('http://127.0.0.1:8001/api/books/contacts/')
        context['contacts'] = response.json()
        return context

    def form_valid(self, form):
        requests.post('http://127.0.0.1:8001/api/books/messages/', data=form.cleaned_data)
        return super().form_valid(form)


class ProfileFormView(TitleMixin, FormView):
    template_name = 'books/profile.html'
    form_class = ProfileForm
    success_url = reverse_lazy('books:profile')
    title = 'Book Store - Profile'
    user_id = None

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        token = self.request.COOKIES.get('Authorization')
        if token:
            req = requests.get('http://127.0.0.1:8000/api/users/login/',
                               headers={'Authorization': f'Token {token}'},
                               params={'token': token})
            context = json.loads(req.text).get('user_data')
            self.user_id = context.get('id')
            kwargs['initial']['first_name'] = context.get('first_name')
            kwargs['initial']['last_name'] = context.get('last_name')
            kwargs['initial']['username'] = context.get('username')
            kwargs['initial']['email'] = context.get('email')
        return kwargs

    def form_valid(self, form):
        requests.patch(f'http://127.0.0.1:8000/api/users/user/{self.user_id}/',
                       headers={'Authorization': f'Token {self.request.COOKIES.get("Authorization")}'},
                       data=form.cleaned_data)
        return super().form_valid(form)


class ReviewTemplateView(TitleMixin, TemplateView):
    template_name = 'books/single-product.html'
    title = 'Book Store - Details'

    def get(self, request, *args, **kwargs):
        book_id = kwargs.get('pk')
        if book_id:
            book = requests.get(f'http://127.0.0.1:8001/api/books/all/{book_id}/')
            self.extra_context = {'book': book.json()}

        return super().get(self, request, *args, **kwargs)

interfaces/books/templates/books/base.html
{% load static %}


<!DOCTYPE html>
	<html lang="en">
	<head>
		<title>{{ title }}</title>
		<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	    <meta name="format-detection" content="telephone=no">
	    <meta name="apple-mobile-web-app-capable" content="yes">
	    <meta name="author" content="">
	    <meta name="keywords" content="">
	    <meta name="description" content="">

	    <link rel="stylesheet" type="text/css" href="{% static 'vendor/css/normalize.css' %}">
	    <link rel="stylesheet" type="text/css" href="{% static 'vendor/icomoon/icomoon.css' %}">
	    <link rel="stylesheet" type="text/css" href="{% static 'vendor/css/vendor.css' %}">
	    <link rel="stylesheet" type="text/css" href="{% static 'vendor/css/style.css' %}">

		<!-- script -->
		<script src="{% static 'vendor/js/modernizr.js' %}"></script>

	</head>

<body>

<div id="header-wrap">

	<div class="top-content">
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<div class="social-links">
						<ul>
							<li>
								<a href="https://facebook.com" target="_blank"><i class="icon icon-facebook"></i></a>
							</li>
							<li>
								<a href="https://twitter.com" target="_blank"><i class="icon icon-twitter"></i></a>
							</li>
							<li>
								<a href="https://youtube.com" target="_blank"><i class="icon icon-youtube-play"></i></a>
							</li>
						</ul>
					</div><!--social-links-->
				</div>
				<div class="col-md-6">
					<div class="right-element">
						<a href="{% if not username %} {% url 'users:login' %} {% else %} {% url 'books:profile' %} {% endif %}"
                           class="user-account for-buy"><i class="icon icon-user"></i><span>
                            {% if username %} {{ username }} {% else %} Account {% endif %}
                        </span></a>
						<a href="{% url 'baskets:basket' %}" class="cart for-buy"><i class="icon icon-clipboard"></i>
                            <span> Basket: ({% if basket_info %} {{ basket_info.total_sum }} {% else %} 0 {% endif %} $)</span>
                        </a>

                        {% if username %}
                            <a href="{% url 'orders:order' %}" class="cart for-buy"><i class="icon icon-paper-plane"></i>
                                <span> Orders</span>
                            </a>
                        {% endif %}

						<div class="action-menu">
							<div class="search-bar">
								<a href="#" class="search-button search-toggle" data-selector="#header-wrap">
									<i class="icon icon-search"></i>
								</a>
								<form role="search" method="get" class="search-box">
									<input class="search-field text search-input" placeholder="Search book" type="search">
								</form>
							</div>
						</div>

					</div><!--top-right-->
				</div>

			</div>
		</div>
	</div><!--top-content-->

	<header id="header">
		<div class="container">
			<div class="row">

				<div class="col-md-2">
					<div class="main-logo">
						<a href="{% url 'books:index' %}"><img src="{% static 'vendor/images/main-logo.png' %}" alt="logo"></a>
					</div>

				</div>

				<div class="col-md-10">

					<nav id="navbar">
						<div class="main-menu stellarnav">
							<ul class="menu-list">
								<li class="menu-item"><a href="{% url 'books:index' %}" data-effect="Home">Home</a></li>
								<li class="menu-item has-sub">
									<a href="{% url 'books:paginator' page=1 category="all"|urlencode %}" class="nav-link" data-effect="Pages">Categories</a>
									<ul>
                                        {% for category in categories %}
								        <li><a href="{% url 'books:paginator' page=1 category=category.name|urlencode|lower %}">{{ category.name }}</a></li>
                                        {% endfor %}
								     </ul>
								</li>
								<li class="menu-item"><a href="{% url 'books:contact' %}" class="nav-link" data-effect="Contact">Contact</a></li>
							</ul>

							<div class="hamburger">
				                <span class="bar"></span>
				                <span class="bar"></span>
				                <span class="bar"></span>
				            </div>

						</div>
					</nav>

				</div>

			</div>
		</div>
	</header>
</div>

{% block content %}
{% endblock %}

<footer id="footer">

</footer>

<script src="{% static 'vendor/js/jquery-1.11.0.min.js' %}"></script>
<script src="{% static 'vendor/js/plugins.js' %}"></script>
<script src="{% static 'vendor/js/script.js' %}"></script>

</body>
</html>

interfaces/books/templates/books/contact.html
{% extends 'books/base.html' %}

{% block content %}
<section>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1 class="page-title">Contact us</h1>
				<div class="breadcrumbs">
					<span class="item"><a href="{% url 'books:index' %}">Home /</a></span>
					<span class="item">Contact us</span>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="contact-information padding-large mt-3">
	<div class="container">
		<div class="row">
			<div class="col-md-6 p-0 mb-3">
				
				<h2>Get in Touch</h2>

				<div class="contact-detail d-flex flex-wrap mt-4">
					<div class="detail mr-6 mb-4">
						<p>Do not be angry with the pain in the reprimand in the pleasure he wants to be a hair from the pain in the hope that there is no breeding. Unless they are blinded by lust, they do not come out; they are in fault who abandon their duties and soften their hearts, that is toil.</p>
						{% for contact in contacts %}
                        <ul class="list-unstyled list-icon">
							<li><i class="icon icon-phone"></i>{{ contact.phone }}</li>
							<li><i class="icon icon-envelope-o"></i><a href="mailto:{{ contact.email }}">{{ contact.email }}</a></li>
							<li><i class="icon icon-location2"></i>
                                {{ contact.street }}, {{ contact.house }}
                                {% if contact.corps %}/ {{ contact.corps }} {% endif %},
                                {{ contact.postal }}
                            </li>
						</ul>
                        {% endfor %}
					</div><!--detail-->
					<div class="detail mb-4">
						<h3>Social Links</h3>
						<div class="social-links flex-container">
							<a href="https://facebook.com" class="icon icon-facebook"></a>&nbsp
							<a href="https://twitter.com" class="icon icon-twitter"></a>&nbsp
							<a href="https://youtube.com" class="icon icon-youtube-play"></a>&nbsp
						</div><!--social-links-->
					</div><!--detail-->

				</div><!--contact-detail-->
			</div><!--col-md-6-->

			<div class="col-md-6 p-0" data-aos="fade-up">
				
				<div class="contact-information">
					<h2>Send A Message</h2>
					<form name="contactform" action="{% url 'books:contact' %}" method="post" class="contact-form d-flex flex-wrap mt-4">
						{% csrf_token %}
                        <div class="row">
					    	<div class="col-md-6">
								{{ form.name }}
							</div>
							<div class="col-md-6">
								{{ form.email }}
							</div>
						</div>

						<div class="row">
							<div class="col-md-12">
								{{ form.message }}
								<label>
								    <input type="checkbox" required>
								    <span class="label-body">I agree all the <a href="#">terms and conditions</a></span>
								</label>

								<button type="submit" name="submit" class="btn btn-full btn-rounded">Submit</button>
							</div>
						</div>
					</form>

				</div><!--contact-information-->

			</div><!--col-md-6-->

		</div>
	</div>
</section>

<section class="google-map">
	<div class="mapouter"><div class="gmap_canvas"><iframe width="100%" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=01033%20Kyiv%20volodymyrska,%2060,%20Kyiv&t=&z=15&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://getasearch.com/fmovies"></a><br><style>.mapouter{position:relative;text-align:right;height:500px;width:100%;}</style><a href="https://www.embedgooglemap.net">embedgooglemap.net</a><style>.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:100%;}</style></div></div>
</section>
{% endblock %}

interfaces/books/templates/books/index.html
{% extends 'books/base.html' %}
{% load static cache humanize %}

{% block content %}
<section id="billboard">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<button class="prev slick-arrow">
					<i class="icon icon-arrow-left"></i>
				</button>
				<div class="main-slider pattern-overlay">
                    {% for preview in previews %}
					<div class="slider-item">
						<div class="banner-content">
							<h2 class="banner-title">{{ preview.name }}</h2>
							<p>{{ preview.description }}</p>
							<div class="btn-wrap">
								<a href="{% url 'books:review' preview.book %}" class="btn btn-outline-accent btn-accent-arrow">Read More<i class="icon icon-ns-arrow-right"></i></a>
							</div>
						</div><!--banner-content--> 
						<img src="{{ preview.image }}" alt="banner" class="banner-image">
					</div><!--slider-item-->
                    {% endfor %}

				</div><!--slider-->
					
				<button class="next slick-arrow">
					<i class="icon icon-arrow-right"></i>
				</button>
				
			</div>
		</div>
	</div>
</section>

<section id="client-holder" data-aos="fade-up">
	<div class="container">
		<div class="row">
			<div class="inner-content">
				<div class="logo-wrap">
					<div class="grid">
                        {% for partner in partners %}
						    <img src="{{ partner.image }}" alt="client">
                        {% endfor %}
					</div>
				</div><!--image-holder-->
			</div>
		</div>
	</div>
</section>

<section id="featured-books">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
                <div class="section-header align-center">
                    <div class="title">
                        <span>Some quality items</span>
                    </div>
                    <h2 class="section-title">Featured Books</h2>
                </div>

                <div class="product-list" data-aos="fade-up">
                    <div class="row">
                        {% for recommendation in recommendations %}
                            <div class="col-md-3">
                                <figure class="product-style">
                                    <a href="{% url 'books:review' recommendation.book %}">
                                        <img src="{{ recommendation.image }}" alt="Book" class="product-item">
                                    </a>
                                    <figcaption>
                                        <h3>{{ recommendation.name }}</h3>
                                        <br>
                                        <div class="item-price">$ {{ recommendation.price | intcomma }}</div>
                                    </figcaption>
                                </figure>
                            </div>
                        {% endfor %}
                    </div><!--ft-books-slider-->
                </div><!--grid-->
			</div><!--inner-content-->
		</div>

		<div class="row">
			<div class="col-md-12">

				<div class="btn-wrap align-right">
					<a href="{% url 'books:shop' category="all"|urlencode %}" class="btn-accent-arrow" target="_blank">View all products <i class="icon icon-ns-arrow-right"></i></a>
				</div>

			</div>
		</div>

	</div>
</section>

<section id="best-selling" class="leaf-pattern-overlay">
	<div class="corner-pattern-overlay"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<div class="row">
					<div class="col-md-6">
						<figure class="products-thumb">
							<img src="{{ books.image }}" alt="book" class="single-image">
						</figure>	
					</div>

					<div class="col-md-6">
						<div class="product-entry">
							<h2 class="section-title divider">Best Selling Book</h2>

							<div class="products-content">
								<h3 class="item-title">{{ books.name }}</h3>
								<p>{{ books.description }}</p>
								<div class="item-price">$ {{ books.price }}</div>
								<div class="btn-wrap">
									<a href="{% url 'books:review' books.id %}" class="btn-accent-arrow">shop it now <i class="icon icon-ns-arrow-right"></i></a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
</section>
{% endblock %}

interfaces/books/templates/books/profile.html
{% extends 'books/base.html' %}
{% load static %}

{% block content %}
    <section>
        <div class="container">

            <div class="row">
                <div style="display: flex; justify-content: space-between;">
                    <h2>Your profile</h2>
                    <a href="{% url 'users:logout' %}" class="nav-link">
                        <h4 style="color: #731A1A;">
                            Exit
                            <img src="{% static 'vendor/images/exit-door-32.png' %}" value="Exit"/>
                        </h4>
                    </a>
                </div>
                <form name="contactform" action="{% url 'books:profile' %}" method="post" class="contact-form d-flex flex-wrap mt-4">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6">
                            {{ form.first_name }}
                        </div>
                        <div class="col-md-6">
                            {{ form.last_name }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            {{ form.username }}
                        </div>
                        <div class="col-md-6">
                            {{ form.email }}
                        </div>
                    </div>
                    <button type="submit" name="submit" class="btn btn-full btn-rounded">Save information</button>
                </form>

            </div><!--contact-information-->

        </div><!--col-md-6-->
    </section>
{% endblock %}

interfaces/books/templates/books/shop.html
{% extends 'books/base.html' %}
{% load cache %}


{% block content %}
<div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">			
				<div class="colored">
					<h1 class="page-title">Shop</h1>
					<div class="breadcum-items">
						<span class="item"><a href="{% url 'books:index' %}">Home /</a></span>
						<span class="item colored">Shop</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div><!--site-banner-->

<section class="padding-large">
	<div class="container">
		<div class="row">

			<div class="products-grid grid">
                {% for book in all_books.results %}
			  	<figure class="product-style">
                    <a href="{% url 'books:review' book.id %}">
                        <img src="{{ book.image }}" alt="Books" class="product-item">
                    </a>
					<figcaption>
						<h3>{{ book.name }}</h3>
						<br>
						<div class="item-price">$ {{ book.price }}</div>
					</figcaption>
				</figure>
                {% endfor %}
	    	</div>

			<div style="display: flex; justify-content: center">
                {% if all_books.previous %}
                <a href="{% url 'books:paginator' category=category page=all_books.page_number|add:-1 %}">
                    <button class="prev slick-arrow" style="margin-right: 10px">
                        <i class="icon icon-arrow-left"></i>
                    </button>
                </a>
                {% endif %}
				<p> </p>
                {% if all_books.next %}
                 <a href="{% url 'books:paginator' category=category page=all_books.page_number|add:1 %}">
                    <button class="next slick-arrow" style="margin-left: 10px">
                        <i class="icon icon-arrow-right"></i>
                    </button>
                </a>
                {% endif %}
			</div>

		</div>
	</div>
</section>
{% endblock %}

interfaces/books/templates/books/single-product.html
{% extends 'books/base.html' %}

{% block content %}
<section class="bg-sand padding-large" data-aos="fade-up">
	<div class="container">
		<div class="row">

            <figure class="product-style" style="pointer-events: none">
                <div class="col-md-4" style="margin-right: 50px">
                    <img class="product-item" src="{{ book.image }}">
                </div>
            </figure>

			<div class="col-md-6 pl-5">
				<div class="product-detail">
					<h1>{{ book.name }}</h1>
					<p> </p>
					<span class="price colored"><b>${{ book.price }}</b></span>
					<p>{{ book.description }}</p>
                    <form action="{% if username %} {% url 'baskets:add' book.id %} {% else %} {% url 'users:login' %} {% endif %}">
                        {% csrf_token %}
                        <button type="submit" class="button">Add to cart</button>
                    </form>

                </div>
            </div>

		</div>
	</div>
</section>
{% endblock %}