interfaces/baskets/urls.py
from django.urls import path

from baskets.views import add_to_basket, remove_from_basket, BasketTemplateView, BasketFormView, SuccessTemplateView

app_name = 'baskets'

urlpatterns = [
    path('current/', BasketTemplateView.as_view(), name='basket'),
    path('current/checkout/', BasketFormView.as_view(), name='checkout'),
    path('current/checkout/success', SuccessTemplateView.as_view(), name='success'),
    path('add-<int:book_id>/', add_to_basket, name='add'),
    path('remove-<int:book_id>/', remove_from_basket, name='remove'),
]

interfaces/books/urls.py
from django.urls import path

from .views import IndexTemplateView, ContactFormView, BooksTemplateView, ReviewTemplateView, ProfileFormView

app_name = 'books'

urlpatterns = [
    path('', IndexTemplateView.as_view(), name='index'),
    path('shop/<str:category>-books/', BooksTemplateView.as_view(), name='shop'),
    path('shop/<str:category>-books/page-<int:page>/', BooksTemplateView.as_view(), name='paginator'),
    path('shop/review/book-<int:pk>/', ReviewTemplateView.as_view(), name='review'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('profile/', ProfileFormView.as_view(), name='profile'),
]

interfaces/interfaces/urls.py
from django.conf import settings
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('', lambda req: redirect('books/')),
    path('books/', include('books.urls', namespace='books')),
    path('users/', include('users.urls', namespace='users')),
    path('baskets/', include('baskets.urls', namespace='baskets')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')),)

interfaces/users/urls.py
from django.shortcuts import redirect
from django.urls import path

from .views import UserLoginFormView, UserRegistrationFormView, EmailVerificationTemplateView

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginFormView.as_view(), name='login'),
    path('logout/', lambda req: redirect('http://127.0.0.1:8000/api/users/logout/'), name='logout'),
    path('registration/', UserRegistrationFormView.as_view(), name='registration'),
    path('verification/<str:email>/<uuid:code>/', EmailVerificationTemplateView.as_view(), name='email_verification'),

    path('accounts/google/', lambda req: redirect('http://127.0.0.1:8000/accounts/google/login/'), name='google'),
    path('accounts/github/', lambda req: redirect('http://127.0.0.1:8000/accounts/github/login/'), name='github'),
]

interfaces/baskets/forms.py
from django import forms


class CheckoutForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'u-full-width',
        'name': 'name',
        'placeholder': 'First Name',
        'minlength': '2',
        'type': 'text',
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'u-full-width',
        'name': 'last_name',
        'placeholder': 'Last Name',
        'type': 'text',
    }))
    email = forms.EmailField(widget=forms.TextInput(attrs={
        'class': 'u-full-width',
        'name': 'email',
        'placeholder': 'E-mail',
        'type': 'email',
    }))
    phone = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'u-full-width',
        'name': 'username',
        'placeholder': 'Phone number',
        'minlength': '2',
        'type': 'text',
    }))
    address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'u-full-width',
        'name': 'username',
        'placeholder': 'Address',
        'minlength': '2',
        'type': 'text',
    }))
    message = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'u-full-width',
        'name': 'message',
        'placeholder': 'Message',
        'style': 'height: 150px',
    }))

interfaces/baskets/views.py
import json
import requests
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView
from rest_framework import status

from baskets.forms import CheckoutForm
from common.views import TitleMixin


class BasketTemplateView(TitleMixin, TemplateView):
    template_name = 'baskets/basket.html'
    title = 'Book Store - Basket'

    def get(self, request, *args, **kwargs):
        token = request.COOKIES.get('Authorization')
        user_id = request.COOKIES.get('User')
        if token and user_id:
            headers = {'Authorization': f'Token {token}'}
            cookies = {'User': user_id}
            response = requests.get('http://127.0.0.1:8003/api/baskets/current/',
                                    headers=headers, cookies=cookies)
            if response.status_code == status.HTTP_200_OK:
                self.extra_context = {'baskets': json.loads(response.text)}
            else:
                return HttpResponseRedirect(request.META['HTTP_REFERER'])
        else:
            return HttpResponseRedirect(request.META['HTTP_REFERER'])
        return super().get(request, *args, **kwargs)


class BasketFormView(TitleMixin, FormView):
    template_name = 'baskets/checkout.html'
    form_class = CheckoutForm
    success_url = reverse_lazy('baskets:success')
    title = 'Book Store - Checkout'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        token = self.request.COOKIES.get('Authorization')
        if token:
            req = requests.get('http://127.0.0.1:8000/api/users/login/',
                               headers={'Authorization': f'Token {token}'},
                               params={'token': token})
            context = json.loads(req.text).get('user_data')
            kwargs['initial']['first_name'] = context.get('first_name')
            kwargs['initial']['last_name'] = context.get('last_name')
            kwargs['initial']['email'] = context.get('email')
        return kwargs

    def form_valid(self, form):
        token = self.request.COOKIES.get('Authorization')
        user_id = self.request.COOKIES.get('User')

        headers = {'Authorization': f'Token {token}'}
        cookies = {'User': user_id}

        get_basket = requests.get('http://127.0.0.1:8003/api/baskets/current/',
                                  headers=headers, cookies=cookies)
        get_total = requests.get('http://127.0.0.1:8003/api/baskets/total/',
                                 headers=headers, cookies=cookies)
        result = {'extra_data': get_basket.text}
        result.update(form.cleaned_data)
        result.update(**json.loads(get_total.text))

        send_order = requests.post('http://127.0.0.1:8004/api/orders/current/',
                                   headers=headers, cookies=cookies, data=result)

        if send_order.status_code == status.HTTP_201_CREATED:
            requests.delete('http://127.0.0.1:8003/api/baskets/current/delete/',
                            headers=headers, cookies=cookies)
            return super().form_valid(form)
        else:
            return HttpResponseRedirect(self.request.META['HTTP_REFERER'])


class SuccessTemplateView(TitleMixin, TemplateView):
    template_name = 'baskets/success.html'
    title = 'Book Store - Checkout Success'


def add_to_basket(request, book_id):
    token = request.COOKIES.get('Authorization')
    user = request.COOKIES.get('User')
    requests.post('http://127.0.0.1:8003/api/baskets/current/',
                  headers={'Authorization': f'Token {token}'},
                  data={'book_id': book_id, 'user_id': user})
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def remove_from_basket(request, book_id):
    token = request.COOKIES.get('Authorization')
    user = request.COOKIES.get('User')
    requests.delete(f'http://127.0.0.1:8003/api/baskets/current/{book_id}/',
                    headers={'Authorization': f'Token {token}'},
                    cookies={'User': user})
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

interfaces/baskets/templates/baskets/basket.html
{% extends 'books/base.html' %}


{% block content %}
<div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="colored">
					<h1 class="page-title">Basket</h1>
					<div class="breadcum-items">
						<span class="item"><a href="{% url 'books:index' %}">Home /</a></span>
						<span class="item colored">Basket</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div><!--site-banner-->

<section class="padding-large">
	<div class="container">
		<div class="row">
			<div class="products-grid grid">
                {% for basket in baskets %}
                    <figure class="product-style">
                        <a href="{% url 'books:review' basket.book_id %}">
                            <img src="{{ basket.image }}" alt="Books" class="product-item">
                        </a>
                        <figcaption>
                            <h3>{{ basket.name }}</h3>
                            <p>Quantity: {{ basket.quantity }}</p>
                            <div class="item-price">$ {{ basket.price }}</div>
                            <form action="{% if username %} {% url 'baskets:remove' basket.id %} {% else %} {% url 'users:login' %} {% endif %}"
                                  style="display: flex; justify-content: center">
                                <button type="submit" class="btn btn-full btn-rounded">Delete</button>
                            </form>
                        </figcaption>
                    </figure>
                {% endfor %}
	    	</div>

            <div class="row">
                {% if baskets %}
                    <form action="{% if username %} {% url 'baskets:checkout' %} {% else %} {% url 'users:login' %} {% endif %}"
                          style="display: flex; justify-content: center">
                        <button type="submit" class="btn btn-full btn-rounded">Checkout</button>
                    </form>
                {% else %}
                    <h2 style="display: flex; justify-content: center">Add some book to fill the basket.</h2>
                {% endif %}
            </div>
		</div>
	</div>
</section>
{% endblock %}

interfaces/baskets/templates/baskets/checkout.html
{% extends 'books/base.html' %}


{% block content %}
<div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="colored">
					<h1 class="page-title">Checkout</h1>
					<div class="breadcum-items">
						<span class="item">
                            <a href="{% url 'books:index' %}">Home /</a>
                            <a href="{% url 'baskets:basket' %}">Basket /</a>
                        </span>
						<span class="item colored">Checkout</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div><!--site-banner-->

<section class="padding-large">
	<div class="container">
		<div class="row">
            <div>
                <h2>Fill in the empty fields</h2>
                <h4>Total quantity: {{ basket_info.total_quantity }}.</h4>
                <h4>Total sum: {{ basket_info.total_sum }}$.</h4>
                <form name="contactform" action="{% url 'baskets:checkout' %}" method="post" class="contact-form d-flex flex-wrap mt-4">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-md-6">
                            {{ form.first_name }}
                        </div>
                        <div class="col-md-6">
                            {{ form.last_name }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            {{ form.email }}
                        </div>
                        <div class="col-md-6">
                            {{ form.phone }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            {{ form.address }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            {{ form.message }}
                        </div>
                    </div>

                    <div class="row">
                        <button type="submit" name="submit" class="btn btn-full btn-rounded">Accept</button>
                    </div>
                </form>
            </div>
		</div>
	</div>
</section>
{% endblock %}

interfaces/baskets/templates/baskets/success.html
{% extends 'users/base.html' %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Congratulations</h3>
                        </div>
                        <div class="card-body text-center">
                            <h4>Your order has been successfully created! The manager will contact you shortly.</h4>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small"><a href="{% url 'books:index' %}">Continue</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}